<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [13]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A):
    for r in range (len(A)):
        for c in range (len(A[r])):
            r,c
    return r , c



def prod(A,B):
    x = matrix_mul(A)
    y = matrix_mul(B)
    if x[1] != y[0]:
        print("A*B = NOT POSSIBLE")
        
    else :
        prod = [[0 for j in range (len(B[0]))] for i in range (len(A))]
        for i in range(len(A)):
   # iterate through columns of Y
            for j in range(len(B[0])):
       # iterate through rows of Y
                for k in range(len(B)):
                    prod[i][j] += A[i][k] * B[k][j]
        print(*prod,sep="\n" )
#A   = [[1 ,2],
    #  [3, 4]]
#B   = [[1 ,4],
     # [5, 6],
     # [7 ,8],
     # [9, 6]]  
#A   = [[1 ,2],
 #     [3, 4]]  
#B   = [[1 ,2, 3, 4, 5],
 #     [5, 6, 7 ,8 ,9]]
    
A   = [[1, 3, 4],
             [2, 5, 7,],
             [5 ,9, 6]]
B   = [[1, 0, 0],
             [0, 1, 0],
             [0, 0, 1]]

prod(A,B)
           

[1, 3, 4]
[2, 5, 7]
[5, 9, 6]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [4]:
def random () :
    import random
    A = [0, 5 ,27, 6, 13, 28 ,100 ,45, 10, 79]        
    S = 0        
    for  i in range (len(A)):
        S = S + A[i]
    Q = random.random()
    print("Randomly genetrated no. from 0 to 1 : {}".format(Q))
        
    P = 0
    x =[]
    for  i in range (len(A)):    
        P += A[i] / S
        x.append(P)
    
    for i in range (len(x)):
        if i < len(x)-1:
            if Q > x[i]:
                if Q <= x[i+1]:
                    print("Randomly generated no. from the given List : {}".format(A[i+1]))
            
            else :
                if Q == x[i]:
                    print("Randomly generated no. from the given List : {}".format(A[i]))
                    
                    
                    
def rand_num ():
    for i in range (0,101):
        r = random ()
        print(r)
        
rand_num()

Randomly genetrated no. from 0 to 1 : 0.6500413009513291
Randomly generated no. from the given List : 45
None
Randomly genetrated no. from 0 to 1 : 0.4452430271931639
Randomly generated no. from the given List : 100
None
Randomly genetrated no. from 0 to 1 : 0.155320377073925
Randomly generated no. from the given List : 13
None
Randomly genetrated no. from 0 to 1 : 0.780737165866067
Randomly generated no. from the given List : 79
None
Randomly genetrated no. from 0 to 1 : 0.3313052039175728
Randomly generated no. from the given List : 100
None
Randomly genetrated no. from 0 to 1 : 0.4195883590387507
Randomly generated no. from the given List : 100
None
Randomly genetrated no. from 0 to 1 : 0.2893844532026042
Randomly generated no. from the given List : 100
None
Randomly genetrated no. from 0 to 1 : 0.7006468739064436
Randomly generated no. from the given List : 45
None
Randomly genetrated no. from 0 to 1 : 0.12735491332614357
Randomly generated no. from the given List : 13
None
Randoml

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [6]:
import re
def replace():
    
    x = re.sub("[a-zA-Z,!,@,#,$,%,^,&,*,(,),?,:,;,\s,'']","",txt)
    y = re.sub("[0-9]","#",x)
    print(x)
    print(y)
    
txt = input("Enter any no.,letter,special character :")
replace()

Enter any no.,letter,special character :822d5ffff;;wk##8
82258
#####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [17]:

s=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
m = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
def display_dash_board(students, marks):
    print("List of students according to descending order of marks :")
x = sorted(zip(s,m),reverse = True ,key= lambda u : u[1])
print(x)
print("           ")
print("a. Who got top 5 ranks, in the descending order of marks :")

print(*x[:5],sep="\n")

print("*****************************************************************************************")

z = sorted(zip(s,m),key = lambda i : i[1])
print("List of students according to Ascending order of marks :")
print(z)
print("                         ")
print("b. Who got least 5 ranks, in the increasing order of marks")

print(*z[:5],sep="\n")

print("*****************************************************************************************")


#print(z[4:8])



for i in range (len(m)):
    r = ((max(m) - min(m)) * 0.25) + min(m)
    c =((max(m) - min(m))* 0.75) + min(m)

print("    ")


print("c. Who got marks between >25th percentile <75th percentile, in the increasing order of marks :")
for i ,j in (sorted(x,key=lambda i : i[1])):
    
    if j > r and j< c:
        print(i,j)
        

[('student8', 98), ('student10', 80), ('student2', 78), ('student5', 48), ('student7', 47), ('student1', 45), ('student6', 43), ('student9', 35), ('student4', 14), ('student3', 12)]
           
a. Who got top 5 ranks, in the descending order of marks :
('student8', 98)
('student10', 80)
('student2', 78)
('student5', 48)
('student7', 47)
*****************************************************************************************
List of students according to Ascending order of marks :
[('student3', 12), ('student4', 14), ('student9', 35), ('student6', 43), ('student1', 45), ('student7', 47), ('student5', 48), ('student2', 78), ('student10', 80), ('student8', 98)]
                         
b. Who got least 5 ranks, in the increasing order of marks
('student3', 12)
('student4', 14)
('student9', 35)
('student6', 43)
('student1', 45)
*****************************************************************************************
    
c. Who got marks between >25th percentile <75th percentile, in the 

<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [11]:
import math


def closest_points_to_p(S, P):
    lst = []
    for x,y in  (S):
        numerator = x*P[0] + y*P[1]
        denomenator = math.sqrt(x*x + y*y) * math.sqrt(P[0]*P[0] + P[1]*P[1])
        cosin_dist = math.acos(numerator/denomenator)
        lst.append(cosin_dist)
    z = (sorted(zip(lst,S),key = lambda i : i[0]))

    print(*z[:5],sep = "\n")
    

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)

(0.06512516333438509, (6, -7))
(0.14189705460416438, (1, -1))
(0.9272952180016123, (6, 0))
(1.2021004241368467, (-5, -8))
(1.4288992721907328, (-1, -1))


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [13]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    for r in (Lines):
        print(r)
        neg_r =[]
        pos_r = []
        for i in (Red):
        
            q = (eval(r.replace('x','*%s'%i[0]).replace('y','*%s'%i[1])))
            if q < 0:
                neg_r.append(q)
            if q > 0:
                pos_r.append(q)
            #print(r  ,  i  ,  q)
        #print(neg_r)
    
        #print("          ")
    
        neg_b =[]
        pos_b = []
        for z in (Blue):
            w = (eval(r.replace('x','*%s'%z[0]).replace('y','*%s'%z[1])))
            if w < 0 :
                neg_b.append(w)
            if w > 0:
                pos_b.append(w)
            #print(r , z , w)
       # print(neg_b)
       # print(" ")
    
        if len(Blue) > len(neg_b) and len(neg_b) != 0:
            print("NO")
        if len(Red) > len(neg_r) and len(neg_r) != 0:
            print("NO")
        if len(Blue) == len(neg_b) and len(Red) == len(pos_r):
            print("YES")
        if len(Red) == len(neg_r) and len(Blue) == len(pos_b):
            print("YES")
    
        print("*************************************")
   
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

i_am_the_one(Red, Blue, i)


1x+1y+0
YES
*************************************
1x-1y+0
NO
NO
*************************************
1x+0y-3
NO
*************************************
0x+1y-0.5
YES
*************************************


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [18]:
def curve_smoothing(string):
    seg = []
    lst = string.split(',')
    for r in range(len(lst)):
        if lst[r] != '_':
            seg.append(r)
    seg.append(len(lst)-1)

    start = 0
    for s in seg:
        int_val = int(lst[s]) if lst[s] != '_' else 0
        int_val += int(lst[start]) if lst[start] != '_' and start!=s else 0
        dist = int_val//(s-start+1)

        lst = [dist if start<=x<=s else lst[x] for x in range(len(lst))]

        start = s
    return lst
S =[ "_,_,_,24","40,_,_,_,60","80,_,_,_,_","_,_,30,_,_,_,50,_,_"]
for i in S:
    z = smoothed_values= curve_smoothing(i)
    print(z)

[6, 6, 6, 6]
[20, 20, 20, 20, 20]
[16, 16, 16, 16, 16]
[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [19]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    lst1=[]
    lst2=[]
    lst3=[]
    for r in A :
        for c in r:
        
            if c == 'S1':
                lst1.append(r)
                #print(lst1)
            if c == 'S2':
                lst2.append(r)
                #print(lst2)
            if c == 'S3':
                lst3.append(r) 
                #print(lst3)
    

    for F in  ('F1','F2','F3','F4','F5'):
        #print(lst1)
        p = lst1.count([F,'S1'])
        print("P(F= {} /S== S1) is : {}/{}".format(F,p,len(lst1)))
        #print(lst2)
        q = lst2.count([F,'S2'])
        print("P(F= {} /S== S2) is : {}/{}".format(F,q,len(lst2)))
        #print(lst3)
        r = lst3.count([F,'S3'])
        print("P(F= {} /S== S3) is : {}/{}".format(F,r,len(lst3)))
    # your code
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F= F1 /S== S1) is : 1/4
P(F= F1 /S== S2) is : 1/3
P(F= F1 /S== S3) is : 0/3
P(F= F2 /S== S1) is : 1/4
P(F= F2 /S== S2) is : 1/3
P(F= F2 /S== S3) is : 1/3
P(F= F3 /S== S1) is : 0/4
P(F= F3 /S== S2) is : 1/3
P(F= F3 /S== S3) is : 1/3
P(F= F4 /S== S1) is : 1/4
P(F= F4 /S== S2) is : 0/3
P(F= F4 /S== S3) is : 1/3
P(F= F5 /S== S1) is : 1/4
P(F= F5 /S== S2) is : 0/3
P(F= F5 /S== S3) is : 0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [20]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    x = S1.split(" ")
    print(x)
    y = S2.split(" ")
    print(y)
    lst=[]
    lst1=[]
    lst2=[]
    for i in range(len(x)):
        for r in range (len(y)):
            if x[i] in y[r]:
                lst.append(x[i])
            
            if x[i] not in y:
                lst1.append(x[i])
            
            if y[r] not in x:       # "!="  is different from   "not in"
                lst2.append(y[r])
            
            
    print(lst)
    print(list(dict.fromkeys(lst1)))
    print(list(dict.fromkeys(lst2)))
    

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
string_features(S1,S2)

['the', 'first', 'column', 'F', 'will', 'contain', 'only', '5', 'uniques', 'values']
['the', 'second', 'column', 'S', 'will', 'contain', 'only', '3', 'uniques', 'values']
['the', 'column', 'will', 'contain', 'only', 'uniques', 'values']
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [24]:
from math import log
def compute_log_loss(A):
    x = 0
    for a,b in A:
        x += (-1 * (a*log(b,10) + (1-a)*log(1-b,10)))
        
    y = x / (len(A))
    print(y)

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
compute_log_loss(A)

0.42430993457031635
